server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/blspringdb?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: bl_spring_admin
    password: db4freeLHN2002
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: org.bill.demoproject.dao.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true



